aliases:
  - name: "ls"
    args: "[path]"
    description: "Directory listing via eza with auto color and directories-first sorting."
  - name: "ll"
    args: "[path]"
    description: "Long all-files listing with custom timestamp format, total size, and octal permissions."
  - name: "la"
    args: "[path]"
    description: "List all files except . and .."
  - name: "l"
    args: "[path]"
    description: "Short listing alias that delegates to ls (which maps to eza)."
  - name: "c"
    args: ""
    description: "Clear the terminal screen."
  - name: "cdc"
    args: ""
    description: "Jump to ~/code."
  - name: "gbr"
    args: ""
    description: "Delete all local git branches except main/master."
  - name: "gcm"
    args: ""
    description: "Checkout master if present, otherwise checkout main."
  - name: "lss"
    args: "[path]"
    description: "Detailed eza listing with long ISO timestamps."
  - name: "h"
    args: "<pattern>"
    description: "Case-insensitive search through shell history."
  - name: "dockernuke"
    args: ""
    description: "Delete all Docker containers/images and prune everything including volumes."
  - name: "pbcopy"
    args: ""
    description: "Copy stdin to the X clipboard (Linux compatibility helper)."
  - name: "pbpaste"
    args: ""
    description: "Output clipboard contents (Linux compatibility helper)."
  - name: "pss"
    args: "<pattern>"
    description: "Process search helper that prints process table header and grep results."
  - name: "pg"
    args: "[-n|--newest] <value>"
    description: "Case-insensitive pgrep by full command line; supports newest-only mode."
  - name: "ssh"
    args: "[ssh args...]"
    description: "Run ssh with TERM forced to xterm-256color."
  - name: "tailscale"
    args: "[tailscale args...]"
    description: "Directly run the macOS Tailscale binary (defined on macOS only)."
  - name: "gclone"
    args: "<repo-url> [destination]"
    description: "Function used by gc/gcl to clone repos with SSH identity selection."
  - name: "gcl"
    args: "<repo-url> [destination]"
    description: "Clone git repo with OpenAI/non-OpenAI SSH key selection flow."
  - name: "gp"
    args: "[git pull args...]"
    description: "Shortcut for git pull."
  - name: "gpull_fn"
    args: "[git pull args...]"
    description: "Function used by gpull alias for smart pull with SSH identity setup."
  - name: "gpull"
    args: "[git pull args...]"
    description: "Smart git pull with optional non-OpenAI SSH identity setup."
  - name: "gc"
    args: "<repo-url> [destination]"
    description: "Alias for gclone."
  - name: "aliases_help"
    args: "[filter text]"
    description: "Function used by aliases to render command metadata."
  - name: "aliases"
    args: "[filter text]"
    description: "Show this alias reference table from .aliases.yml."
