aliases:
  - name: "ls"
    args: "[path]"
    description: "Directory listing via eza with auto color and directories-first sorting."
  - name: "ll"
    args: "[path]"
    description: "Long all-files listing with custom timestamp format, total size, and octal permissions."
  - name: "la"
    args: "[path]"
    description: "List all files except . and .."
  - name: "l"
    args: "[path]"
    description: "Short listing alias that delegates to ls (which maps to eza)."
  - name: "c"
    args: ""
    description: "Clear the terminal screen."
  - name: "celar"
    args: ""
    description: "Typo-friendly alias for clear."
  - name: "cdc"
    args: ""
    description: "Jump to ~/code."
  - name: "gbr"
    args: ""
    description: "Delete local branches except current, main/master, and origin default branch."
  - name: "gcm"
    args: ""
    description: "Switch to repo default branch (origin/HEAD), with main/master fallback and remote tracking support."
  - name: "lss"
    args: "[path]"
    description: "Detailed eza listing with long ISO timestamps."
  - name: "h"
    args: "[pattern]"
    description: "No args: show full history. With args: case-insensitive history search via rg."
  - name: "dockernuke"
    args: ""
    description: "Remove all containers/images when present, then run docker system prune including volumes."
  - name: "pg"
    args: "[-n|--newest] <pattern>"
    description: "Primary process searcher with highlighted matches and PID/USER/CPU/MEM/ELAPSED/COMMAND columns."
  - name: "ssh"
    args: "[ssh args...]"
    description: "Run ssh with TERM forced to xterm-256color via command ssh."
  - name: "tailscale"
    args: "[tailscale args...]"
    description: "Directly run the macOS Tailscale binary."
  - name: "gclone"
    args: "<repo-url> [destination]"
    description: "Function used by gc/gcl to clone repos with SSH identity selection."
  - name: "gcl"
    args: "<repo-url> [destination]"
    description: "Clone git repo with OpenAI/non-OpenAI SSH key selection flow."
  - name: "gp"
    args: "[git pull args...]"
    description: "Shortcut for git pull."
  - name: "gpull_fn"
    args: "[git pull args...]"
    description: "Function used by gpull alias for smart pull with SSH identity setup."
  - name: "gpull"
    args: "[git pull args...]"
    description: "Smart git pull with optional non-OpenAI SSH identity setup."
  - name: "gc"
    args: "<repo-url> [destination]"
    description: "Alias for gclone."
  - name: "aliases_help"
    args: "[filter text]"
    description: "Function used by aliases to render command metadata."
  - name: "aliases"
    args: "[filter text]"
    description: "Show this alias reference table from .aliases.yml."
