Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/InfiniteLoop:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
