---
version: 2
updates:
  - package-ecosystem: bundler
    vendor: true
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
      day: monday
      time: "21:00"
      timezone: America/Los_Angeles
    groups:
      prod-ruby-dependencies:
        dependency-type: production
        patterns:
          - "*"
      dev-ruby-dependencies:
        dependency-type: development
        patterns:
          - "*"
    cooldown:
      default-days: 45
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: weekly
      day: tuesday
      time: "21:00"
      timezone: America/Los_Angeles
    cooldown:
      default-days: 45
