---
name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: harden runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # pin@v2.19.4
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            github.com:443
            release-assets.githubusercontent.com:443
          disable-sudo-and-containers: true

      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6
        with:
          persist-credentials: false

      - name: setup ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # pin@v1.310.0
        with:
          ruby-version: .ruby-version
          bundler: none
          bundler-cache: false

      - name: bootstrap
        run: script/bootstrap

      - name: test
        run: script/test
