---
name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: openai/fence@db291f5c51949e6e6ec1634621b36dc4bbf3d54a # pin@v0.8.7

      - name: checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # pin@v6
        with:
          persist-credentials: false

      - name: setup ruby
        uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # pin@v1.312.0
        with:
          ruby-version: .ruby-version
          bundler: none
          bundler-cache: false

      - name: bootstrap
        run: script/bootstrap

      - name: test
        run: script/test
